apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: secrets-VAR_SERVICE_NAME
  namespace: VAR_NAMESPACE_KUBERNETES
spec:
  provider: aws
  parameters:
    region: sa-east-1
    objects: |
      - objectName: "staging/eks/VAR_NAMESPACE_KUBERNETES/VAR_SERVICE_NAME"
        objectType: "secretsmanager"
        jmesPath:
          - path: "DB_USER"
            objectAlias: "DB_USER"
          - path: "DB_PASSWORD"
            objectAlias: "DB_PASSWORD"
  secretObjects:
    - secretName: secrets-VAR_SERVICE_NAME
      type: Opaque
      data:
        - objectName: "DB_USER"
          key: "DB_USER"
        - objectName: "DB_PASSWORD"
          key: "DB_PASSWORD"
